task seed_training_providers: :environment do
  
 [['3aaa', 'applynorwich@3aaa.co.uk'],
  ['Active Development Education', 'darrencox@adeducation.co.uk'],
  ['All Trades Training', 'enquiries@alltradestraining.co.uk'],
  ['Anglian Academy of Hair', 'Laura.smith@broadland.gov.uk'],
  ['Anne Clarke Associates', 'support@anneclarkeltd.co.uk'],
  ['Apprentice Funding Assistant', 'afahr@apprenticefunding.com'],
  ['Apprenticeships Broadland', 'Laura.smith@broadland.gov.uk'],
  ['Babcock International', 'eofeadmin@babcockinternational.com'],
  ['BPP', 'apprenticeshipqueries@bpp.com'],
  ['CITB', 'myapprenticeship@citb.co.uk'],
  ['City College Norwich', 'recruitapprentice@ccn.ac.uk'],
  ['Colchester Institute', 'apprenticeships@colchester.ac.uk'],
  ['Connect2 Care', 'Sue.york@connect2care.net'],
  ['Constructions Training Specialists', 'Laura.smith@broadland.gov.uk'],
  ['Develop', 'hegartyc@developebp.co.uk'],
  ['Easton & Otley College', 'Business.solutions@eastonotley.ac.uk'],
  ['First4Skills', 'info@first4skills.com'],
  ['Great Yarmouth College', 'employerservices@gyc.ac.uk'],
  ['HIT Training', 'info@hittraining.co.uk'],
  ['Intraining', 'apprenticeships@intraining.co.uk'],
  ['ITS', 'laura.oreilly@felixstowe-ac.co.uk'],
  ['JG Plummer', 'Laura.smith@broadland.gov.uk'],
  ['JTL', 'markrudling@jtltraining.com'],
  ['Kaplan Financial', 'norwich@kaplan.co.uk'],
  ['Learndirect', 'Stuart.goudge@learndirect.com'],
  ['Lowestoft College', 'info@lowestoft.ac.uk'],
  ['Norfolk Community Learning Services', 'Andrew.norman@norfolk.gov.uk'],
  ['Norfolk Training Services', 'apprenticeships@norfolktrainingservices.co.uk'],
  ['Nova Training', 'dominic.keeney@novatraining.co.uk'],
  ['People and Business Development', 'info@pbdevelopment.co.uk'],
  ['Poultec Training', 'enquiries@poultec.co.uk'],
  ['Qube Learning', 'futuretalent@qube-learning.co.uk'],
  ['Swarm Apprenticeships', 'futuretalent@qube-learning.co.uk'],
  ['Remit', 'apprenticeships@remit.co.uk'],
  ['Skillnet', 'info@skillnet.org.uk'],
  ['Steadfast Training', 'info@steadfasttraining.co.uk'],
  ['The College of West Anglia', 'Jane.howling@cwa.ac.uk'],
  ['West Suffolk College', 'apprenticeships@wsc.ac.uk'],
  ['WS Training', 'apprenticeships@wstraining.co.uk'],
  ['YMCA Training', 'Amanda.bowie@ymca.co.uk'],
  ['Needham Market Academy', 'robert.peace@needhammarketfcacademy.co.uk'],
  ['Learn a Living', 'richard.carruthers@learnaliving.co.uk'],
  ['Lifeskillssolutions', 'leon@lifeskillssolutions.net'],
  ['University Campus Suffolk', 'k.hinton@UCS.ac.uk'],
  ['Key Training', 'joseph.sutton@keytraining.co.uk'],
  ['Right Direction Training', 'john@rightdirectiontraining.co.uk'],
  ['Bluesky', 'jane@janebluesky.co.uk'],
  ['Suffolk New College', 'heidihodgson@suffolk.ac.uk'],
  ['Keits', 'emily.cullum@keits.co.uk'],
  ['MEAT East', 'meat.ipswich.ltd@btclick.com'],
  ['BRS', 'duncan@brs.org.uk'],
  ['DS Training', 'darren.cox@ds-training.org' ],
  ['Carter Academy', 'claire.skipper@rgcarter.co.uk'],
  ['CSV', 'bmacgregor@csv.org.uk'],
  ['Tomorrows People', 'aedwards@tomorrows-people.co.uk']].each do |name, email|
    TrainingProvider.create!(name: name, email: email)
  end

end